version: "2"
run:
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - dupl
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - ireturn
    - reassign
    - testpackage
  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          allow:
            - $gostd
            - github.com/weastur
            - github.com/goccy/go-yaml
          deny:
            - pkg: math/rand$
              desc: use math/rand/v2
    forbidigo:
      forbid:
        - pattern: ^print(ln)?$
      exclude-godoc-examples: true
      analyze-types: true
    paralleltest:
      ignore-missing: true
      ignore-missing-subtests: true
    varnamelen:
      ignore-decls:
        - t testing.T
        - e error
        - i int
        - T any
        - w http.ResponseWriter
        - r *http.Request
        - wg sync.WaitGroup
    wsl:
      allow-cuddle-with-calls:
        - Done
        - Add
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
          - funlen
          - gocognit
          - gosec
          - varnamelen
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
